/**
 * EXERCISE 3: Event Name Derivation
 * 
 * We often want to build a strongly-typed `on(eventName, callback)` bus
 * automatically derived from a nested state object.
 * 
 * GOAL:
 * 1. Implement `NestedPaths<T>` that returns all dot-notation paths for an object.
 *    e.g. { user: { name: string, age: number } } -> 'user.name' | 'user.age'
 * 2. Implement `EventNames<T>` that attaches `'Changed'` to the end of the paths.
 *    -> 'user.nameChanged' | 'user.ageChanged'
 */

// 1. NestedPaths
// Hint: For each key K in keyof T:
// If T[K] is an object (and not a primitive), it's `${K}.${NestedPaths<T[K]>}`
// Otherwise, it's just `K`.
// Note: Intersect K with string (`K & string`) to avoid Symbol/Number issues.
export type NestedPaths<T> = T; // FIX ME

// 2. EventNames
// Take the union generated by NestedPaths and append 'Changed'.
export type EventNames<T> = T; // FIX ME

// Usage example (Do not edit):
export declare function on<T, P extends EventNames<T>>(
    state: T,
    event: P,
    callback: () => void
): void;
